Add a situation (and foldedSteps) migration function
EmileRolley/publiopti pull request #39
Opened 2024-05-14 13:24 UTC by bjlaa

2024-05-14 14:02 UTC, Clemog commented
Je me charge de tester l'implé dans le site de NGC pour tester ? 
Est ce qu'on ajoute ici des tests unitaires ?

2024-05-15 06:15 UTC, florianpanchout reviewed
Est-ce que cette fonction ne devrait pas aussi détecter les règles qui ne sont pas valides  ? (mais pas incluses dans les instructions de migration). En plus de la situation et des foldedSteps "vraiment" propre, on pourrait retourner un array contenant les règles non gérées.

Aussi avoir ce safeGetSituation dans ce repo permettrait d'exporter un autre utils `safelyAddSituation` qui prendrait comme props une situation, l'objet d'option de addSituation, un engine et les règles. Ensuite il n'y aurait plus qu'à utiliser exclusivement cette fonction pour ajouter à la situation.

2024-05-15 11:59 UTC, bjlaa commented
> Je me charge de tester l'implé dans le site de NGC pour tester ? 

@Clemog j'ai testé de mon côté en local en buildant `tools` et en filant son path dans le package.json du site ; j'ai l'impression que tout roule, même avec mes simulations de septembre 2023, mais je suis preneur de ton avis et de ton oeil de lynx ici !

2024-05-15 12:31 UTC, florianpanchout commented on source/migrations/migrateSituation.ts
> +      const result = handleSituationKeysMigration({
`const { situationMigrated, foldedStepsMigrated } =` non ?

2024-05-15 12:36 UTC, florianpanchout approved these changes

2024-05-15 14:08 UTC, Clemog commented on source/migrations/migrateSituation.ts
> +      const result = handleSituationKeysMigration({
Je crois que ce n'est pas possible car on utilise `situationMigrated`, `foldedStepsMigrated` dans les arguments

2024-05-15 14:38 UTC, EmileRolley commented
Hmm, pourquoi vous voulez ajouter la gestion des migrations dans ce dépôt ? Pour l'instant, il me semble que c'est propre à NGC la notion de migration non ?

2024-05-15 14:38 UTC, Clemog approved these changes

2024-05-15 14:44 UTC, Clemog commented
> Hmm, pourquoi vous voulez ajouter la gestion des migrations dans ce dépôt ? Pour l'instant, il me semble que c'est propre à NGC la notion de migration non ?

On s'est posé la question de le mettre dans nosgestesclimat-scripts

Ça peut etre utile pour d'autres projets, c'est assez indépendant de NGC finalement donc j'ai poussé pour que ce soit ici

2024-05-15 14:44 UTC, EmileRolley requested changes
Par soucis d'homogénéité ce serait bien si vous pouviez adopter les même conventions que pour le reste de la lib. Je pense également qu'il faudrait le séparer dans un module à part et pas exposer les fonction à la racine (comme pour `/optims` et `/compilation`).

2024-05-15 14:45 UTC, Clemog commented
On a besoin de cette fonction dans 2 dépôts, ça me semblait le plus pertinent

Pourquoi tu verrais ça vraiment très spécifique à NGC ?

2024-05-15 14:46 UTC, EmileRolley commented
> > Hmm, pourquoi vous voulez ajouter la gestion des migrations dans ce dépôt ? Pour l'instant, il me semble que c'est propre à NGC la notion de migration non ?
> 
> On s'est posé la question de le mettre dans nosgestesclimat-scripts
> 
> Ça peut etre utile pour d'autres projets, c'est assez indépendant de NGC finalement donc j'ai poussé pour que ce soit ici

Oui c'est vrai que ça peut être utile à d'autre projet. Dans ce cas il faudrait créer un module à part entière et documenter le cas d'usage etc..

2024-05-15 14:47 UTC, Clemog commented
Ah yes effectivement, on n'a pas de doc, c'est pas ouf (j'ai l'impression que c'est pas ton kiff @bjlaa 😇)

2024-05-15 14:48 UTC, Clemog commented
> Je pense également qu'il faudrait le séparer dans un module à part et pas exposer les fonction à la racine (comme pour `/optims` et `/compilation`).

C'est à dire ?

2024-05-15 14:52 UTC, EmileRolley commented
> > Je pense également qu'il faudrait le séparer dans un module à part et pas exposer les fonction à la racine (comme pour `/optims` et `/compilation`).
> 
> C'est à dire ?

Les exposer dans un sous-chemin pour les importer depuis `@publicodes/tools/migration` : 

https://github.com/publicodes/tools/blob/ee4e38a0f74dd4a337a21822ae980f0338fab686/package.json#L18-L33

Vous pouvez regarder ce qui est fait pour `optims` et `compilation`. Leurs `index.ts` ne sont pas exposés dans l'index racine et cela permet également de rajouter la documentation relative au module : https://github.com/publicodes/tools/blob/main/source/optims/index.ts

2024-05-15 15:00 UTC, Clemog commented
Ok merci je regarde ça

2024-05-15 15:35 UTC, Clemog commented
Comment on peut vérifier l'affichage et tout ?

2024-05-15 18:13 UTC, EmileRolley commented
> Comment on peut vérifier l'affichage et tout ?

En générant la doc (`yarn run docs`) ?

2024-05-16 07:09 UTC, Clemog commented
> En générant la doc (`yarn run docs`) ?

Yes j'avais vu cette commande mais j'ai rien qui se lance pour voir la doc ..? Désolé j'ai l'impression de louper un truc con 😅

2024-05-16 07:32 UTC, Clemog approved these changes

2024-05-16 07:59 UTC, Clemog commented
@EmileRolley on merge car on a besoin d'utiliser la fonction en P0, on peut revenir dessus sans souci :)

2024-05-16 08:31 UTC, merged